### ISSUE TITLE
经常性的崩溃导致无法发送消息。

### ISSUE THREAD

**Issue by telppa** [MrXiaoM/fpv#2]
### 问题描述

经常性的崩溃导致无法发送消息。

报错信息如下

`2024-12-03 10:46:19 I/trpgbot.adapter.ws: Bot(******) request_token, IAA 云天明 章北海 赵怡然### Astral Protection Core: 由于系统近期检测到这段时间有来自未知流量的非法攻击，为了保护其他用户的正常使用，较大资源消耗的IP将被限制，如需需要添加IP白名单请联系签名维护者 https://mirai.mamoe.net/topic/2673/qsign-9-0-55-9-0-95-%E5%85%AC%E7%9B%8A-api%E5%8F%91%E5%B8%83
2024-12-03 10:46:19 E/trpgbot.adapter.ws: kotlinx.serialization.json.internal.JsonDecodingException: Expected class kotlinx.serialization.json.JsonArray as the serialized body of kotlin.collections.ArrayList, but had class kotlinx.serialization.json.JsonObject
kotlinx.serialization.json.internal.JsonDecodingException: Expected class kotlinx.serialization.json.JsonArray as the serialized body of kotlin.collections.ArrayList, but had class kotlinx.serialization.json.JsonObject
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.beginStructure(TreeJsonDecoder.kt:330)
        at kotlinx.serialization.json.internal.JsonTreeDecoder.beginStructure(TreeJsonDecoder.kt:259)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:29)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:61)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:52)
        at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:25)
        at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:117)
        at trpgbot-1.13.4.mirai2.jar//xyz.cssxsh.mirai.tool.adapters.QsignWebSocketAdapter.requestToken(WebSocketAdapter.kt:89)
        at trpgbot-1.13.4.mirai2.jar//xyz.cssxsh.mirai.tool.adapters.AbstractAdapter$signRegister$1.invokeSuspend(AbstractAdapter.kt:109)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
`

### 复现

登录后什么都不做。

### mirai-core 版本

2.16

### bot-protocol

ANDROID_PAD

### 签名服务

默认服务，没有动过。

### 系统日志

```plain text
2024-12-03 10:46:19 I/trpgbot.adapter.ws: Bot(******) request_token, IAA 云天明 章北海 赵怡然### Astral Protection Core: 由于系统近期检测到这段时间有来自未知流量的非法攻击，为了保护其他用户的正常使用，较大资源消耗的IP将被限制，如需需要添加IP白名单请联系签名维护者 https://mirai.mamoe.net/topic/2673/qsign-9-0-55-9-0-95-%E5%85%AC%E7%9B%8A-api%E5%8F%91%E5%B8%83
2024-12-03 10:46:19 E/trpgbot.adapter.ws: kotlinx.serialization.json.internal.JsonDecodingException: Expected class kotlinx.serialization.json.JsonArray as the serialized body of kotlin.collections.ArrayList, but had class kotlinx.serialization.json.JsonObject
kotlinx.serialization.json.internal.JsonDecodingException: Expected class kotlinx.serialization.json.JsonArray as the serialized body of kotlin.collections.ArrayList, but had class kotlinx.serialization.json.JsonObject
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.beginStructure(TreeJsonDecoder.kt:330)
        at kotlinx.serialization.json.internal.JsonTreeDecoder.beginStructure(TreeJsonDecoder.kt:259)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:29)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:61)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:52)
        at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:25)
        at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:117)
        at trpgbot-1.13.4.mirai2.jar//xyz.cssxsh.mirai.tool.adapters.QsignWebSocketAdapter.requestToken(WebSocketAdapter.kt:89)
        at trpgbot-1.13.4.mirai2.jar//xyz.cssxsh.mirai.tool.adapters.AbstractAdapter$signRegister$1.invokeSuspend(AbstractAdapter.kt:109)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```

**Comment by telppa** [comment]
又崩了一次，以下是日志，可以看到登录成功后就什么都没做，然后40分钟整后，崩了。

`2024-12-03 11:17:21 I/main: mirai-console started successfully.
2024-12-03 11:57:21 I/trpgbot.adapter.ws: Bot(******) request_token, IAA 云天明 章北海 赵怡然### Astral Protection Core: 由于系统近期检测到这段时间有来自未知流量的非法攻击，为了保护其他用户的正常使用，较大资源消耗的IP将被限制，如需需要添加IP白名单请联系签名维护者 https://mirai.mamoe.net/topic/2673/qsign-9-0-55-9-0-95-%E5%85%AC%E7%9B%8A-api%E5%8F%91%E5%B8%83
2024-12-03 11:57:21 E/trpgbot.adapter.ws: kotlinx.serialization.json.internal.JsonDecodingException: Expected class kotlinx.serialization.json.JsonArray as the serialized body of kotlin.collections.ArrayList, but had class kotlinx.serialization.json.JsonObject
kotlinx.serialization.json.internal.JsonDecodingException: Expected class kotlinx.serialization.json.JsonArray as the serialized body of kotlin.collections.ArrayList, but had class kotlinx.serialization.json.JsonObject
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.beginStructure(TreeJsonDecoder.kt:330)
        at kotlinx.serialization.json.internal.JsonTreeDecoder.beginStructure(TreeJsonDecoder.kt:259)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:29)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:61)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:52)
        at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:25)
        at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:117)
        at trpgbot-1.13.4.mirai2.jar//xyz.cssxsh.mirai.tool.adapters.QsignWebSocketAdapter.requestToken(WebSocketAdapter.kt:89)
        at trpgbot-1.13.4.mirai2.jar//xyz.cssxsh.mirai.tool.adapters.AbstractAdapter$signRegister$1.invokeSuspend(AbstractAdapter.kt:109)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)`
![25](https://github.com/user-attachments/assets/7d901362-0316-4143-8502-1228fba33f08)
